FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

RUN echo '<html><body><h1>Arborisis API</h1></body></html>' > /usr/share/nginx/html/index.html
RUN echo 'ok' > /usr/share/nginx/html/health

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
